---
title: "Final Project"
author: "Bridget Silha"
date: "11/7/2019"
output: pdf_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

require(httr)
require(tidyverse)
#install.packages("remotes")
#remotes::install_github("robinspollak/R.openFEC")

#Make API request
my_api_key <- "O1j8sCGbgjwe6GNd0026VW9az9J5Ssv2X8l3DCN8"
URL <- "https://api.open.fec.gov/v1/committees/?sort_nulls_last=false&sort=name&page=1&sort_null_only=false&per_page=100&api_key=gWb11FjhJGZqJNjtWyI2We24GIl9ybUQxHUYuxFr&sort_hide_null=false"
get.data <- GET(URL, query=list(api_key=my_api_key))
fec.data <- content(get.data)

#pull pages temporary data set out
pages <- fec.data[["pagination"]][["pages"]]
data_raw <- c()
for (p in 1:length(pages)){
  tmp_url <- paste0("https://api.open.fec.gov/v1/committees/?sort_nulls_last=false&sort=name&page=", 
         p,
         "&sort_null_only=false&per_page=100&api_key=", 
         my_api_key, 
         "&sort_hide_null=false")
  tmp.get.data <- GET(tmp_url, query=list(api_key=my_api_key))
  tmp.fec.data <- content(tmp.get.data)[["results"]]
  for(i in 1:length(tmp.fec.data)){
  tmp <- tmp.fec.data[[i]] %>% 
    unlist() %>% 
    enframe() %>% 
    mutate(page_entry = paste0(p, "_", i),
           page = p,
           entry = i)
  data_raw <- bind_rows(data_raw,tmp)
  }
  Sys.sleep(sample(seq(.5,2,0.5), 1))
}


data_raw <- data_raw %>% 
  select (-page_entry, -page, -entry)



#Spread data
data_raw <- data_raw %>% 
  spread(., key = name, value = value, fill = NA)

```


```{r}
#Read CVS data in
total_fec_committee_party_and_pac <- read_csv("committees.csv")
pac_financial_info_2018 <- read_csv("committee_summary_2018.csv")

##Clean Data
#https://www.fec.gov/campaign-finance-data/committee-type-code-descriptions/ 

#Select PAC Committee Types
total_fec_committee_party_and_pac <- total_fec_committee_party_and_pac %>% 
  filter(committee_type == "N" | committee_type == "O" | committee_type == "Q" | committee_type == "V" | committee_type == "W")

#Join on Committee ID
new_data_2018 <- right_join(total_fec_committee_party_and_pac, pac_financial_info_2018, by=c("committee_id" = "CMTE_ID"))

#Cut down variables
new_data_2018 <- new_data_2018 %>% 
  select(-cycles, -treasurer_name, -filing_frequency:-affiliated_committee_name)

new_data_2018 <- new_data_2018 %>% 
  select (-Link_Image, -CMTE_ST1:-CMTE_CITY, -CMTE_ZIP:-CAND_ID, -INDV_CONTB:-OTH_CMTE_CONTB, -TRANF_FROM_OTHER_AUTH_CMTE:-OTHER_RECEIPTS, -TRANF_TO_OTHER_AUTH_CMTE:-OTHER_DISB, -NET_CONTB:-TTL_COMMUNICATION_COST)

skimr::skim(new_data_2018)
```

```{r}
#Read CVS data in
total_fec_committee_party_and_pac <- read_csv("committees.csv")
pac_financial_info_2020 <- read_csv("committee_summary_2020.csv")

##Clean Data
#https://www.fec.gov/campaign-finance-data/committee-type-code-descriptions/ 

#Join on Committee ID
new_data_2020 <- right_join(total_fec_committee_party_and_pac, pac_financial_info_2020, by=c("committee_id" = "CMTE_ID"))

#Cut down new variables
new_data_2020 <- new_data_2020 %>% 
  select(-cycles, -treasurer_name, -filing_frequency:-affiliated_committee_name)

new_data_2020 <- new_data_2020 %>% 
  select (-Link_Image, -CMTE_ST1:-CMTE_CITY, -CMTE_ZIP:-CAND_ID, -INDV_CONTB:-OTH_CMTE_CONTB, -TRANF_FROM_OTHER_AUTH_CMTE:-OTHER_RECEIPTS, -TRANF_TO_OTHER_AUTH_CMTE:-OTHER_DISB, -NET_CONTB:-TTL_COMMUNICATION_COST)


skimr::skim(new_data_2020)
```


```{r}
#Bind 2018 and 2020 datasets together
new_data <- bind_rows(new_data_2018, new_data_2020)

#Filter for party type
new_data <- new_data %>% 
  filter(party == "DEM" | party == "REP" | party == "CRV" | party == "lIB" | party == "IAP" | party == "REF")

#Filter for committee type
new_data <- new_data %>% 
  filter(CMTE_TP == "N" | CMTE_TP == "O" | CMTE_TP == "Q" | CMTE_TP == "V" | CMTE_TP == "W")
```



```{r}
#split into training and test data
train_dat = dat %>% filter(date < as.Date("2017-06-01"))
test_dat = dat %>% filter(date >= as.Date("2017-06-01"))

dim(train_data)
```

